### ISSUE TITLE
can we get this to work in the browser ?

### ISSUE THREAD

**Issue by minanagehsalalma** [NoYzE1/jwpacrack#1]

**Comment by NoYzE1** [comment]
Since it's written in java one could make a java-applet to run inside the browser from it. However java need to be installed and activated in the browser for it to work and is discouraged even by oracle itself for having many security issues.

Much more convenient for modern day use would be a port or transpilation to JavaScript, which practically runs inside any browser. The only problem here is the input of the pcap and dictionary file, since browsers rightfully prevent access from local ressources to scripts. Supplying the files from a url could result in a cross-site-scripting warning or prevention by the browser. So if you solve this issue it should be no problem. But note, that such use would be for educational purposes only.

**Comment by minanagehsalalma** [comment]
@NoYzE1  Thanks I found a js script that does this a while ago.
